[package]
name = "vpncloud"
version = "0.8.1"
authors = ["Dennis Schwerdel <schwerdel@informatik.uni-kl.de>"]
build = "build.rs"
license = "GPL-3.0"
description = "Peer-to-peer VPN"
homepage = "https://github.com/dswd/vpncloud.rs"
repository = "https://github.com/dswd/vpncloud.rs"
keywords = ["vpn", "p2p", "tun", "tap", "network"]
readme = "README.md"

[dependencies]
time = "0.1"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
log = "0.3"
libc = "0.2"
aligned_alloc = "0.1"
rand = "0.3"
fnv = "1"
net2 = "0.2"
bitflags = "0.8"
igd = "0.6"
siphasher = "0.2"
daemonize = "0.2"
mio = "0.6"
nix = "0.8"

[build-dependencies]
pkg-config = "0.3"

[features]
default = []
bench = []
system-libsodium = []

[profile.release]
lto = true

[profile.dev]
lto = false

[profile.test]
lto = false
